### ISSUE TITLE
Unknown field type "edd_license".

### ISSUE THREAD

**Issue by pagelab** [firetreedesign/carbon-field-edd-license#10]
Hi, I'm receiving this error message when using your add-on in a test theme.

![image](https://user-images.githubusercontent.com/1451087/128572738-61c9d727-8a66-4ccb-9f1b-cd449f64bf83.png)

I'm using Composer 2.0.13 and Carbon Fields 3.3.

`composer.json`
```json
{
    "name": "test-theme/theme",
    "require": {
        "htmlburger/carbon-fields": "^3.3",
        "firetreedesign/carbon-field-edd-license": "^1.0.3"
    }
}
```

`functions.php`
```php
<?php

require_once( get_parent_theme_file_path( 'vendor/autoload.php' ) );

use Carbon_Fields\Container;
use Carbon_Fields\Field;


add_action( 'after_setup_theme', 'crb_load' );
function crb_load() {
    \Carbon_Fields\Carbon_Fields::boot();
}

add_action( 'carbon_fields_register_fields', 'crb_attach_theme_options' );
function crb_attach_theme_options() {
    Container::make( 'theme_options', __( 'Theme Options' ) )
        ->add_fields( array(
            Field::make( 'text', 'crb_text', 'Text Field' ),
            Field::make( 'edd_license', 'my_license_key', __( 'My License Key' ) )
                ->set_plugin_file( __FILE__ )
                ->set_item_id( 224 )
                ->set_version( '1.0.0' )
                ->set_store_url( 'https://firetreedesign.com/' )
                ->set_author( __( 'FireTree Design, LLC' ) )
                ->set_beta( false )
        ) );
}
```

[theme-test.zip](https://github.com/firetreedesign/carbon-field-edd-license/files/6948028/theme-test.zip)

**Comment by danielmilner** [comment]
It looks like this is an issue with using the field in a theme. The field is registered during "plugins_loaded", but the theme files don't run until after that hook has already run, so the field is never registered. I need to see if moving the field registration to "after_theme_setup" has any negative effects.
